# Generated by Django 6.0.7 on 2026-07-14 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_question', models.CharField(choices=[('mascota', '¿Cuál fue el nombre de tu primera mascota?'), ('escuela', '¿Cuál fue el nombre de tu escuela primaria?'), ('ciudad', '¿En qué ciudad naciste?'), ('madre', '¿Cuál es el segundo nombre de tu madre?'), ('comida', '¿Cuál es tu comida favorita?')], max_length=50)),
                ('security_answer', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
