# Generated by Django 6.0.7 on 2026-07-21 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_security_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pregunta_seguridad',
            field=models.CharField(blank=True, choices=[('mascota', '¿Cuál era el nombre de tu primera mascota?'), ('ciudad', '¿En qué ciudad naciste?'), ('escuela', '¿Cuál era el nombre de tu primera escuela?'), ('amigo', '¿Cuál era el nombre de tu mejor amigo de la infancia?'), ('comida', '¿Cuál es tu comida favorita?')], default='', max_length=50, verbose_name='Pregunta de seguridad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='respuesta_seguridad',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Respuesta de seguridad'),
        ),
    ]
